### ISSUE TITLE
STAT500 Manual

### ISSUE THREAD

**Issue by PMeaghan** [RobinHankin/stat500#5]
Hi Robin - 

Not sure if this is the appropriate place for a suggested STAT500 course manual correction. I think the below labels need to be flipped negative skew with positive skew and the below picture comment, swapping 'left-skewed distribution' and 'right skewed distribution' in the sentence placement.

My understanding is the below but please correct me if I am incorrect!
Negative skew = mean < median < mode
Positive skew =  mean > median > mode

![image](https://user-images.githubusercontent.com/48575517/54403183-f9b7fe80-4733-11e9-8995-b3af4bdc1121.png).

Many thanks,

Paige Gilmore

**Comment by RobinHankin** [comment]
you are absolutely correct and I'll fix it when I get a minute. Thanks!
